services:
  app:
    image: ghcr.io/aryanaggg/cicd-demo:latest
    # image: ghcr.io/aryanaggg/cicd-demo:df34ac14ce54b6e646eb33c41f86ea19df9cea2b
    container_name: cicd-demo
    ports:
      - "5000:5000"
      # host -> container
    restart: unless-stopped
  
  # redis:
  #   image: redis:7-alpha